name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main  # Change this to your default branch if different

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version your project uses

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the React application
      - name: Build
        run: npm run build

      # Step 5: Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Optional, provided by GitHub
          action: "upload"
          app_location: "/" # Location of your application code
          output_location: "build" # Location of the build output
